// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp6nSOeqcoOpUoVAiaDMt3jDW7qsmkIQY',
    appId: '1:966773388468:web:2dfd31318f3096c7af53e1',
    messagingSenderId: '966773388468',
    projectId: 'dolzarb100-f50a5',
    authDomain: 'dolzarb100-f50a5.firebaseapp.com',
    storageBucket: 'dolzarb100-f50a5.firebasestorage.app',
    measurementId: 'G-6207P2HVWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2a2pRxNKvty88Tw9rGlzlJQF3J-Gnzdg',
    appId: '1:966773388468:android:c1b6e1ecabd9784faf53e1',
    messagingSenderId: '966773388468',
    projectId: 'dolzarb100-f50a5',
    storageBucket: 'dolzarb100-f50a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBbdiz9zcG9s0whzEPPSZINdWMF5pZ2OI',
    appId: '1:966773388468:ios:605ebf90be87f1b1af53e1',
    messagingSenderId: '966773388468',
    projectId: 'dolzarb100-f50a5',
    storageBucket: 'dolzarb100-f50a5.firebasestorage.app',
    iosBundleId: 'com.example.dolzarb100Kun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBbdiz9zcG9s0whzEPPSZINdWMF5pZ2OI',
    appId: '1:966773388468:ios:605ebf90be87f1b1af53e1',
    messagingSenderId: '966773388468',
    projectId: 'dolzarb100-f50a5',
    storageBucket: 'dolzarb100-f50a5.firebasestorage.app',
    iosBundleId: 'com.example.dolzarb100Kun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp6nSOeqcoOpUoVAiaDMt3jDW7qsmkIQY',
    appId: '1:966773388468:web:80de3834c75608e3af53e1',
    messagingSenderId: '966773388468',
    projectId: 'dolzarb100-f50a5',
    authDomain: 'dolzarb100-f50a5.firebaseapp.com',
    storageBucket: 'dolzarb100-f50a5.firebasestorage.app',
    measurementId: 'G-0Z04E6L9ER',
  );
}
